### ISSUE TITLE
render of (foo+,bar) with 0 repeats not correct

### ISSUE THREAD

**Issue by seanyoung** [bengtmartensson/IrpTransmogrifier#222] opened 2022-12-28 11:28 UTC
If we have an IRP with an repeating `+` part, you expect it to be rendered once even with 0 repeats, like so:
```
$ ./irptransmogrifier.sh --irp '{100}<1|3>(2,-1,(4,-1)+)[]' render -r --number-repeats 0
[+200,-100,+400,-100]
```
This also works:
```
$ ./irptransmogrifier.sh --irp '{100}<1|3>((3,-1),(2,-1)+,(4,-1))[]' render -r --number-repeats 0
[+300,-100,+200,-100,+400,-100]
```

However if we have an up part and no down part, this is broken:
```
$ ./irptransmogrifier.sh --irp '{100}<1|3>((2,-1)+,(4,-1))[]' render -r --number-repeats 0
[+400,-100]
```

**Comment by seanyoung** [comment] 2022-12-28 12:39
Just to be clear, I expected this:

```
$ ./irptransmogrifier.sh --irp '{100}<1|3>((2,-1)+,(4,-1))[]' render -r --number-repeats 0
[+200,-100,+400,-100]
```

**Comment by bengtmartensson** [comment] 2022-12-29 09:31
Hi Sean. Thank you for the report. I can confirm it, and probably it should be fixed. It turns out it is because of a (questionable) feature in IrSignal.java, line 193
 
```
  // If the given intro sequence is identical to the repeat sequence, reject it.
  this.introSequence = ((introSequence != null) && !introSequence.approximatelyEquals(repeatSequence)) ? introSequence : new IrSequence();
```
The fix is obvious and easy. Let me think for a few days if it may have any side effects. Again, thank you very much!

**Comment by seanyoung** [comment] 2022-12-29 09:56
Wonderful, thank you very much. I've got some automated testing that compares the [cir IRP encoder](https://github.com/seanyoung/cir) to IrpTransmogrifier and this trips it up. Please let me know if I can help.

**Closed** 2023-01-07 10:53 UTC

**Comment by bengtmartensson** [comment] 2023-01-07 10:57
The obvious fix applied, which should solve this issue, as well as #223. 

Thank you very much again for your report on this!
