### ISSUE TITLE
Infinite bitfield gives bad error message

### ISSUE THREAD

**Issue by seanyoung** [bengtmartensson/IrpTransmogrifier#229] opened 2023-02-05 16:06 UTC
I discovered this with fuzz testing. It's just a nice to have.

```bash
$ ./irptransmogrifier.sh --irp '{40k,msb}<-1|1>(155::4,-50)' render -r
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "org.harctoolbox.irp.IrStreamItem.stateWhenEntering(org.harctoolbox.ircore.IrSignal$Pass)" because "irStreamItem" is null
```

A useful error message would be much nicer than an exception.

**Comment by bengtmartensson** [comment] 2023-02-05 21:14
Hi Sean,

thank you for this report. The problem is that the IRP "language" (both the verbal description and the ANTLR grammar) accepts infinite bitfields as elements of IrStreams, although it not really makes any sense semantically. A real fix would be to address this. At the current maturity state of IrpTransmogrifier, I am reluctant to tweak the grammar without a very good reason. You appear to be of the same opinion, since you ask for better error message.

I agree that the current behaviour is ugly and should be fixed. I will have to think of this for some time. Will get back to you.

**Comment by seanyoung** [comment] 2023-02-05 21:52
The way I solved it (for now) in the rust implementation is that I walk the irp after parsing to ensure it only contains expressions that make sense. That way, rather than "parse error", you get a more descriptive error saying that a particular expression is not permitted in a stream/bitspec. See https://github.com/seanyoung/cir/blob/9428c60cb7c14c2043c148e06f70c592b4d0a6cb/irp/src/parser.rs#L548

**Comment by bengtmartensson** [comment] 2023-02-06 18:51
Actually, I would like to simplify the grammar as per https://github.com/bengtmartensson/IrpTransmogrifier/blob/master/src/main/doc/IRPNotationV3.odt . This would mean eliminating the "infinite bitfields" -- to my knowledge it is only used to left-shift integers anyhow, and "<<" is a better notation for this. But I am hesitant to dig up this -- 20 years ago things would have been different.

**Comment by seanyoung** [comment] 2023-02-07 08:56
That is good point: `::` is only used for (right) shifting in expressions, and could be removed. However, I am no sure a search and replace of `::` with `>>` would work in `IrpProtocols.xml`. `<<` has a very different precedence level than `::`.

It is rather ugly to have two operators which the same function in the language, and also with differing precedence levels, so removing it would be nice.

**Closed** 2023-02-12 21:03 UTC
Labels: Feedback solicited, Annoyance

**Comment by bengtmartensson** [comment] 2023-02-12 21:12
$ java -jar target/IrpTransmogrifier-1.2.12-SNAPSHOT-jar-with-dependencies.jar   --irp '{40k,msb}<-1|1>(155::4,-50)' render -r
    Infinite Bitfield 155::4 cannot be put into an IrStream.

not a really perfect solution (throws a non-checked exception), but it does what you  asked for.
